### ISSUE TITLE
使用过程中遇到的一些问题

### ISSUE THREAD

**Issue by YRSB** [slqy123/ASMRManager#5]
开发者你好，我最近尝试使用了这个程序，在使用过程中遇到一些问题：

首先是用```pip install ASMRManager```安装并运行```asmr```后，没有自动生成示例的配置文件和 sql 文件
![屏幕截图 2024-05-26 203248](https://github.com/slqy123/ASMRManager/assets/32013347/422b08a5-53fa-4142-9844-858b2a21b1eb)

我自己手动创建文件夹、把文件复制过去并修改配置文件后，输入```asmr``` 可以运行了，但是我遇到了第二个问题：
我尝试运行```asmr info RJ01180045```，但是又报错了：
![屏幕截图 2024-05-26 203908](https://github.com/slqy123/ASMRManager/assets/32013347/e66010ac-faa7-494b-ad03-61d9c038577f)

我本机上其实是有自己配置过的 aria2 的，配置完 port 和 secret 发现一运行就报这个错误
然后我又尝试了pip install 的 那个aria2，结果也是报同样的错误

**Comment by slqy123** [comment]
第一个是循环引用的bug，之前修复过，但好像不知道什么时候又不小心改出bug了。

第二个似乎是由于你没有在设置里将download_method设置为aria2。

这两个问题目前（2.0.2）都修复了，现在就算是用idm也不会在使用info命令的时候报错了。
运行`pip install --upgrade ASMRManager[aria2]`即可。
