### ISSUE TITLE
请问只能一页一页拉取吗?

### ISSUE THREAD

**Issue by 300git** [slqy123/ASMRManager#6]
我看了下使用说明,
下载的页码 `asmr dl search -p` 只能选择单个整数, 而不能选择区间
目前我使用您的软件, 只能一页一页的拉取, 拉完一页（20个音声）之后, 还要手动换到下一页,  
不知道是不是我没搞对,还是本来就是这样设置的

例：想要拉取一位声优的所有音频， 但是她的作品有很多页，每页20个
因此我使用`asmr dl search -v 声优 `拉取后， 默认只下了第一页， 
 我加上参数`-p`后，也只能2.3.4.5这样一页一页的搞，不能更多

**Comment by slqy123** [comment]
确实只能一页一页爬取，如果需要爬取全部可以考虑写个脚本，例如用powershell：
```powershell
for ($i=1;$i -le 10;$i++) { asmr dl search -v xxx -p $i}
```
这个脚本就是爬取前十页。

获取全部实现起来也不难，找个时间加上吧

**Comment by slqy123** [comment]
升级到 2.2.0 版本，使用 `-p 0` 就可以下载全部了。
```
pip install --upgrade ASMRManager
或者
pipx upgrade ASMRManager
```
