### ISSUE TITLE
【功能建议】建议【文件过滤】增加判断

### ISSUE THREAD

**Issue by 300git** [slqy123/ASMRManager#7]
有些音声， 只有WAV格式，没有MP3格式。
于是当【文件过滤】 设置了过滤WAV， 就会导致整个音声都没有下载东西

建议提供一个判断， 当音声没有MP3时， 尽管设置过滤了WAV格式，依然强制下载WAV格式，保证至少有东西下

反过来同理（当过滤了MP3，但音声没有WAV，就强制下载MP3）

**Comment by slqy123** [comment]
这个功能我也在考虑，目前初步的想法是为每个filter添加一个选项，在没有任何音频文件被下载的时候选择是否禁用这个filter。但稍微有点复杂就一直拖着，这两天研究研究看看吧。
