### ISSUE TITLE
【BUG】未考虑关键词的-排除特性

### ISSUE THREAD

**Issue by 300git** [slqy123/ASMRManager#8]
原网站 使用`-关键词`可以排除不想要的内容
使用您的软件, 在使用命令`asmr dl search -中文版 --subtitle  -s 500: --force --all -p 0`时, 

> 其中`-中文版`是关键词, 
> 全句含义: 所有500销量以上,并且有字幕,但是标题不要含中文版

错误的把`-中文版`当成了可选参数
从而报错:

> 2024-10-05 19:47:33 - INFO - Run program with: dl search -中文版 --subtitle -s 500: --force --all -p 0
> Usage: asmr dl search [OPTIONS] [TEXT]
> Try 'asmr dl search -h' for help.
> 
> Error: No such option: -中

且config文件的过滤设置, 只有tag,文件名,文件夹
测试在文件夹`range = "directory"`过滤加入过滤`中文`的正则, 对标题含有关键词`中文`无效。

版本：2.2.2

建议，关键词可以使用引号来区分可选参数`‘关键词’`

**Comment by slqy123** [comment]
升级到2.2.4版本，使用`!`代替`-`，即`!中文版`即可过滤。另还添加了`--duration`的支持。

至于过滤设置问题，目前并无相关打算，如果某个搜索组合经常使用的话，可以在shell中为其创建一个别名，例如 powershell 中：
```powershell
code $PROFILE # 使用vscode编辑profile文件
function asmr-search-cn { asmr dl search 中文版 @args}  # 将这个函数粘贴进去
```
重启shell就可以使用 `asmr-search-cn` 命令了。
